server:
  port: 8018

spring:
  datasource:
    url: jdbc:mysql://114.55.102.111:3306/springbootdb?characterEncoding=utf8&useSSL=false
    username: root
    password: 147258
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
